### ISSUE TITLE
Canary deployment causing 503s after reaching 100% setWeight

### ISSUE THREAD

**Issue by deathsurgeon1** [argoproj/argo-rollouts#3586] opened 2024-05-19 10:49 UTC
Checklist:

* [ ] I've included steps to reproduce the bug.
* [ ] I've included the version of argo rollouts.

**Describe the bug**

I am using below deployment configuration for canary deployment in our service. The deployment works fine till the last set of canary pods are marked as healthy. I am also using **dynamicStableScale = true** so as soon as canary pods comes up the required number of pods are getting removed from stable deployment which is our requirement. 

However as soon as last batch of canary pods come up, the deployment starts deleting the last set of remaining pods in stable rollout. At this point of time, i am seeing 503s at this exact moment and once pods are deleted 503s are gone. Sharing the deployment configuration below:

> kind: Rollout
apiVersion: argoproj.io/v1alpha1
metadata:
  labels:
    env: prf-use2-eks
  name: rollout
spec:
  replicas: null
  strategy:
    canary:
      dynamicStableScale: true
      antiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: { }
      canaryMetadata:
        labels:
          state: canary
      maxSurge: 10
      maxUnavailable: 0
      steps:
      - setCanaryScale:
          replicas: 3
      - pause: {}
      - setWeight: 15
      - pause:
          duration: 60s
      - setCanaryScale:
          matchTrafficWeight: true
      - setWeight: 25
      - pause:
          duration: 60s
      - setWeight: 35
      - pause:
          duration: 120s
      - setWeight: 50
      - pause:
          duration: 120s
      - setWeight: 75
      - pause:
          duration: 120s
      - setWeight: 100
      - pause:
          duration: 240s
      trafficRouting:
        alb:
          ingress: rpas-rollout-ingress
          rootService: rpas-root-service
          servicePort: 443
        istio:
          virtualService:
            name: rpas-rollout-vsvc

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

**Logs**

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by mybliss** [comment] 2024-06-14 03:26
I also met this issue on our env. this is our rollout configuration. 
`apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Rollout
  metadata:
    generation: 44
    labels:
      app.kubernetes.io/managed-by: Helm
    name: collector
  spec:
    replicas: 2
    restartAt: "2024-06-13T08:16:55Z"
    revisionHistoryLimit: 5
    rollbackWindow:
      revisions: 3
    selector:
      matchLabels:
        app.kubernetes.io/component: collector
    strategy:
      canary:
        canaryService: collector-canary
        stableService: collector
        steps:
        - setWeight: 10
        - pause:
            duration: 2m
        - setWeight: 20
        - pause:
            duration: 2m
        - setWeight: 50
        - pause:
            duration: 1h
        - setWeight: 100
        - pause:
            duration: 1h
        - setCanaryScale:
            matchTrafficWeight: true
        trafficRouting:
          nginx:
            additionalIngressAnnotations:
              canary-by-header: X-Canary
              canary-by-header-value: goodluck
            stableIngress: collector-nginx
    workloadRef:
      apiVersion: apps/v1
      kind: Deployment
      name: collector`

      I tested if I removed the last pause step, and there is no 503 errors.

**Comment by jessesuen** [comment] 2024-09-30 23:42
Duplicate of https://github.com/argoproj/argo-rollouts/issues/3586

**Closed by jessesuen** 2024-09-30 23:42 UTC
Labels: bug, canary
