### ISSUE TITLE
Using canary w/ dynamic stable scale causes failed requests at end of rollout

### ISSUE THREAD

**Issue by Bennett-Lynch** [argoproj/argo-rollouts#3681] opened 2024-06-27 00:47 UTC
**Describe the bug**

Hello,

I recently enabled Istio-based traffic routing and the `dynamicStableScale` feature on my application. The feature works as described except it is causing a brief period of failed requests at the end of the rollout.

My spec is roughly as follows:

```
spec:
  strategy:
    canary:
      trafficRouting: { istio: { ... } }
      # Scale down stable replica set as the traffic weight increases to canary
      dynamicStableScale: true
      # Run background analysis throughout rollout
      analysis: ...
      steps:
        # Create 1 canary replica for testing purposes
        - setCanaryScale: { replicas: 1 }
        # Run in-line analysis against canary replica
        - analysis: ...
        # Returns to the default behavior of matching the canary traffic weight
        - setCanaryScale: { matchTrafficWeight: true }
        # Scale up the canary
        - setWeight: 25
        - pause: { duration: 5m }
        - setWeight: 50
        - pause: { duration: 5m }
        - setWeight: 75
        - pause: { duration: 5m }
        - setWeight: 100
        # Pause post-deployment to allow background analysis to evaluate 100% weight
        - pause: { duration: 5m }
```

What I'm repeatedly observing is that as soon as the canary weight is increased to 100%, the last stable replica will be scaled down and clients to the service will encounter "no healthy upstream" Istio errors for approximately 30 seconds. I believe this occurs at a rate proportional to the most recent weight increase, or about 25% in the above example. I suspect the 30 seconds may be partly due to Istio propagation delay but propagation is usually within a few seconds.

Is this intended behavior? Is there anything I can configure to allow my stable endpoint sufficient time to drain before fully scaling it down?

More specifically, I want the behavior of `dynamicStableScale` (so that I am not running 2x my baseline number of replicas), but I want to ensure that the stable replica set is left with at least 1 healthy/ready replica for a draining period after its traffic weight is set to 0%.

Configuration options I've looked at but don't seem to quite fit:
1. `minReadySeconds` (defaults to 0, so this may help, but what if canary reaches full replica size in a previous step due to rounding?)
2. `maxUnavailable` (defaults to 1, so does not appear to be used after going to 100%)
3. `scaleDownDelaySeconds` (default is 30s, but errors appear immediately after going to 100%)
4. `minPodsPerReplicaSet` (defaults to 1, so does not appear to be used after going to 100%)

**Version**

1.7.0

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by gghcode** [comment] 2024-06-27 08:29
This looks like the same [issue](https://github.com/argoproj/argo-rollouts/issues/3586) as your issue.

**Comment by Bennett-Lynch** [comment] 2024-06-27 15:28
Thanks @gghcode. It does seem related. Have you tried testing without a pause step after 100% weight, like @mybliss mentioned? Not that that's an viable workaround but it may provide some more clues to what is causing this to happen.

**Comment by Bennett-Lynch** [comment] 2024-06-27 23:59
I was able to prevent the errors by removing the final pause step. I don't consider this a viable workaround since the final pause step is needed to evaluate the deployment at 100% weight. However it may be helpful information for diagnosing the underlying issue.

**Comment by Bennett-Lynch** [comment] 2024-07-02 21:56
After more testing, this issue only seems to occur when both:
1. `dynamicStableScale` is enabled
2. there is a pause step after setting the canary weight to 100%

**Comment by wmuizelaar** [comment] 2024-07-08 11:20
Might possibly be fixed by https://github.com/argoproj/argo-rollouts/pull/3602 as well.

**Comment by wmuizelaar** [comment] 2024-07-18 08:10
I also saw it on follow up deployments as well.

-- 
Kind regards,
Wietse

**Comment by nithin-john-porter** [comment] 2024-08-15 17:47
is this fixed where i can use both:

1.dynamicStableScale is enabled
2.there is a pause step after setting the canary weight to 100%

**Comment by Bennett-Lynch** [comment] 2024-08-16 14:45
@nithin-john-porter It has not been fixed yet to the best of my knowledge.

**Comment by nithin-john-porter** [comment] 2024-08-16 18:54
@kostis-codefresh could you help here?

**Comment by jessesuen** [comment] 2024-09-30 23:42
Duplicate of https://github.com/argoproj/argo-rollouts/issues/3586

**Closed by jessesuen** 2024-09-30 23:42 UTC
Labels: bug, canary

**Comment by insylogo** [comment] 2024-11-07 23:55
Are you serious that you don't plan on fixing this? It's a serious bug and if the answer is "well don't wait after you set weight to 100" then you need to enforce that programmatically when the rollout is invoked, don't just break anyone who is waiting at the end of the rollout.

**Comment by jeanmorais** [comment] 2024-12-05 22:58
Same problem here.

We use Istio with DestinationRule subsets, and we don't set pause after 100%. 

As soon as the traffic shifts to 100% some clients receive `no healthy upstream`.

**Comment by kostis-codefresh** [comment] 2024-12-06 07:57
I have done some preliminary investigation on this and I am not even sure if it an Argo Rollouts bug or an Istio problem. In particular updating to the latest version of Istio (1.24) seems to reduce the period of "no healthy upstream" in a signifant manner.

On a related note, the current workaround I have found is to use host level splitting https://argo-rollouts.readthedocs.io/en/stable/features/traffic-management/istio/#host-level-traffic-splitting

**Comment by AFMiziara** [comment] 2024-12-06 17:14
We had the same problem, but the issue in our case was that we were using extra labels on `DestinationRule` to control the subsets instead of relying only on `rollouts-pod-template-hash`. This way everytime the traffic shifted to 100%, there was a small delay when reconciliating the pods with the custom label, which caused `no health upstream`. So we solved by removing this extra label we had.
