### ISSUE TITLE
Inline Analysis starts before preview pod is ready

### ISSUE THREAD

**Issue by nestorsokil** [argoproj/argo-rollouts#811] opened 2020-11-01 22:03 UTC
## Summary 

What happened/what you expected to happen?
This is my config:
```yaml
strategy:
    canary:
      stableService: {{ template "app.name" . }}
      canaryService: {{ template "app.name" . }}-canary
      trafficRouting:
        nginx:
          stableIngress: {{ template "app.name" . }}.grpc
      analysis:
        startingStep: 2
        templates:
          - templateName: {{ template "app.name" . }}-error-rate
          - templateName: {{ template "app.name" . }}-latency
      steps:
        - analysis:
            templates:
              - templateName: {{ template "app.name" . }}-acceptance
        - setWeight: 10
        - pause: { duration: 2m }
        - setWeight: 25
        - pause: { duration: 2m }
        - setWeight: 50
        - pause: { duration: 2m }
```
The problem is that the `acceptance-test` analysis run kicks in before the new Pod reaches Ready state.
```
NAME                                                               KIND         STATUS        AGE    INFO
⟳ argomyapp                                                         Rollout      ✖ Degraded    29m
├──# revision:2
│  ├──⧉ argomyapp-58c746787b                                        ReplicaSet   • ScaledDown  29m
│  └──α argomyapp-58c746787b-2-1-argomyapp-acceptance                AnalysisRun  ✖ Failed      29m    ✖ 1
│     └──⊞ 2c7a6675-e046-4ab6-80e5-cf9840526276.acceptance-test.1  Job          ✖ Failed      29m
└──# revision:1
   └──⧉ argomyapp-6594b78d49                                        ReplicaSet   ✔ Healthy     36m    stable
      └──□ argomyapp-6594b78d49-7w67w                               Pod          ✔ Running     36m    ready:1/1
```

## Diagnostics

What version of Argo Rollouts are you running?
`0.9.2`

# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>

```
time="2020-11-01T21:57:43Z" level=info msg="Started syncing rollout at (2020-11-01 21:57:43.46631058 +0000 UTC m=+700316.756187735)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Canary steps change detected (new: 5f98485f4d, old: 5f86645d5)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=warning msg="Assuming 7cb9fcbbf8 for new replicaset pod hash" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Canary steps change detected (new: 5f98485f4d, old: 5f86645d5)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Patched: {\"status\":{\"abort\":null,\"abortedAt\":null,\"canary\":{\"currentStepAnalysisRun\":null,\"currentStepAnalysisRunStatus\":null},\"conditions\":[{\"lastTransitionTime\":\"2020-11-01T21:27:30Z\",\"lastUpdateTime\":\"2020-11-01T21:27:30Z\",\"message\":\"Rollout has minimum availability\",\"reason\":\"AvailableReason\",\"status\":\"True\",\"type\":\"Available\"},{\"lastTransitionTime\":\"2020-11-01T21:57:43Z\",\"lastUpdateTime\":\"2020-11-01T21:57:43Z\",\"message\":\"Rollout \\\"argomyapp\\\" is progressing.\",\"reason\":\"ReplicaSetUpdated\",\"status\":\"True\",\"type\":\"Progressing\"}],\"currentPodHash\":\"7cb9fcbbf8\",\"currentStepHash\":\"5f98485f4d\",\"observedGeneration\":\"77d675c7c7\"}}" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Reconciliation completed" namespace=myapp rollout=argomyapp time_ms=15.152488
time="2020-11-01T21:57:43Z" level=info msg="Started syncing rollout at (2020-11-01 21:57:43.481755364 +0000 UTC m=+700316.771632525)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Updating replica set 'argomyapp-7cb9fcbbf8' revision to 3" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Cleaning up old replicasets, experiments, and analysis runs" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Switched selector for service 'argomyapp-canary' to value '7cb9fcbbf8'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="No changes to canary ingress - skipping patch" ingress=argomyapp-argomyapp.grpc-canary namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Reconciling StableRS" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Reconciling new ReplicaSet 'argomyapp-7cb9fcbbf8'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Reconciling old replica sets" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Rollout has reached the desired state for the correct weight" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Incrementing the Current Step Index to 1" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Patched: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2020-11-01T21:27:30Z\",\"lastUpdateTime\":\"2020-11-01T21:27:30Z\",\"message\":\"Rollout has minimum availability\",\"reason\":\"AvailableReason\",\"status\":\"True\",\"type\":\"Available\"},{\"lastTransitionTime\":\"2020-11-01T21:57:43Z\",\"lastUpdateTime\":\"2020-11-01T21:57:43Z\",\"message\":\"ReplicaSet \\\"argomyapp-7cb9fcbbf8\\\" is progressing.\",\"reason\":\"ReplicaSetUpdated\",\"status\":\"True\",\"type\":\"Progressing\"}],\"currentStepIndex\":1}}" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Reconciliation completed" namespace=myapp rollout=argomyapp time_ms=43.312256
time="2020-11-01T21:57:43Z" level=info msg="Started syncing rollout at (2020-11-01 21:57:43.525110899 +0000 UTC m=+700316.814988061)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Cleaning up old replicasets, experiments, and analysis runs" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="No changes to canary ingress - skipping patch" ingress=argomyapp-argomyapp.grpc-canary namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Created AnalysisRun for step '1'" analysisrun=argomyapp-7cb9fcbbf8-3-1 namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Reconciling StableRS" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Reconciling new ReplicaSet 'argomyapp-7cb9fcbbf8'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:43Z" level=info msg="Reconciling old replica sets" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Patched: {\"status\":{\"canary\":{\"currentStepAnalysisRun\":\"argomyapp-7cb9fcbbf8-3-1\",\"currentStepAnalysisRunStatus\":{\"name\":\"argomyapp-7cb9fcbbf8-3-1\",\"status\":\"\"}}}}" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciliation completed" namespace=myapp rollout=argomyapp time_ms=754.239286
time="2020-11-01T21:57:44Z" level=info msg="Started syncing rollout at (2020-11-01 21:57:44.279401933 +0000 UTC m=+700317.569279091)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Cleaning up old replicasets, experiments, and analysis runs" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="No changes to canary ingress - skipping patch" ingress=argomyapp-argomyapp.grpc-canary namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciling StableRS" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciling new ReplicaSet 'argomyapp-7cb9fcbbf8'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciling old replica sets" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="No status changes. Skipping patch" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciliation completed" namespace=myapp rollout=argomyapp time_ms=3.6836909999999996
time="2020-11-01T21:57:44Z" level=info msg="Started syncing rollout at (2020-11-01 21:57:44.286214984 +0000 UTC m=+700317.576092155)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Cleaning up old replicasets, experiments, and analysis runs" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="No changes to canary ingress - skipping patch" ingress=argomyapp-argomyapp.grpc-canary namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciling StableRS" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciling new ReplicaSet 'argomyapp-7cb9fcbbf8'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciling old replica sets" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="No status changes. Skipping patch" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciliation completed" namespace=myapp rollout=argomyapp time_ms=3.2739230000000004
time="2020-11-01T21:57:44Z" level=info msg="Started syncing rollout at (2020-11-01 21:57:44.480047506 +0000 UTC m=+700317.769924657)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Cleaning up old replicasets, experiments, and analysis runs" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="No changes to canary ingress - skipping patch" ingress=argomyapp-argomyapp.grpc-canary namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciling StableRS" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciling new ReplicaSet 'argomyapp-7cb9fcbbf8'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:44Z" level=info msg="Reconciling old replica sets" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Patched: {\"status\":{\"canary\":{\"currentStepAnalysisRunStatus\":{\"status\":\"Running\"}}}}" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciliation completed" namespace=myapp rollout=argomyapp time_ms=598.3628570000001
time="2020-11-01T21:57:45Z" level=info msg="Started syncing rollout at (2020-11-01 21:57:45.07846288 +0000 UTC m=+700318.368340029)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Cleaning up old replicasets, experiments, and analysis runs" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="No changes to canary ingress - skipping patch" ingress=argomyapp-argomyapp.grpc-canary namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling StableRS" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling new ReplicaSet 'argomyapp-7cb9fcbbf8'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling old replica sets" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="No status changes. Skipping patch" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciliation completed" namespace=myapp rollout=argomyapp time_ms=3.588964
time="2020-11-01T21:57:45Z" level=info msg="Started syncing rollout at (2020-11-01 21:57:45.085262831 +0000 UTC m=+700318.375139992)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Cleaning up old replicasets, experiments, and analysis runs" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="No changes to canary ingress - skipping patch" ingress=argomyapp-argomyapp.grpc-canary namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling StableRS" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling new ReplicaSet 'argomyapp-7cb9fcbbf8'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling old replica sets" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="No status changes. Skipping patch" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciliation completed" namespace=myapp rollout=argomyapp time_ms=3.12688
time="2020-11-01T21:57:45Z" level=info msg="Started syncing rollout at (2020-11-01 21:57:45.276156288 +0000 UTC m=+700318.566033439)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Cleaning up old replicasets, experiments, and analysis runs" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="No changes to canary ingress - skipping patch" ingress=argomyapp-argomyapp.grpc-canary namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling StableRS" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling new ReplicaSet 'argomyapp-7cb9fcbbf8'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling old replica sets" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="No status changes. Skipping patch" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciliation completed" namespace=myapp rollout=argomyapp time_ms=3.444696
time="2020-11-01T21:57:45Z" level=info msg="Started syncing rollout at (2020-11-01 21:57:45.476280095 +0000 UTC m=+700318.766157234)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Cleaning up old replicasets, experiments, and analysis runs" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="No changes to canary ingress - skipping patch" ingress=argomyapp-argomyapp.grpc-canary namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling StableRS" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling new ReplicaSet 'argomyapp-7cb9fcbbf8'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciling old replica sets" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="No status changes. Skipping patch" namespace=myapp rollout=argomyapp
time="2020-11-01T21:57:45Z" level=info msg="Reconciliation completed" namespace=myapp rollout=argomyapp time_ms=3.606566
time="2020-11-01T21:58:05Z" level=info msg="Started syncing rollout at (2020-11-01 21:58:05.317253394 +0000 UTC m=+700338.607130560)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Cleaning up old replicasets, experiments, and analysis runs" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="No changes to canary ingress - skipping patch" ingress=argomyapp-argomyapp.grpc-canary namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciling StableRS" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciling new ReplicaSet 'argomyapp-7cb9fcbbf8'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciling old replica sets" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Patched: {\"status\":{\"abort\":true,\"abortedAt\":\"2020-11-01T21:58:05Z\",\"canary\":{\"currentStepAnalysisRunStatus\":{\"message\":\"metric \\\"acceptance-test\\\" assessed Failed due to failed (1) \\u003e failureLimit (0)\",\"status\":\"Failed\"}},\"conditions\":[{\"lastTransitionTime\":\"2020-11-01T21:27:30Z\",\"lastUpdateTime\":\"2020-11-01T21:27:30Z\",\"message\":\"Rollout has minimum availability\",\"reason\":\"AvailableReason\",\"status\":\"True\",\"type\":\"Available\"},{\"lastTransitionTime\":\"2020-11-01T21:58:05Z\",\"lastUpdateTime\":\"2020-11-01T21:58:05Z\",\"message\":\"metric \\\"acceptance-test\\\" assessed Failed due to failed (1) \\u003e failureLimit (0)\",\"reason\":\"RolloutAborted\",\"status\":\"False\",\"type\":\"Progressing\"}],\"currentStepIndex\":0}}" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciliation completed" namespace=myapp rollout=argomyapp time_ms=14.784903
time="2020-11-01T21:58:05Z" level=info msg="Started syncing rollout at (2020-11-01 21:58:05.338764361 +0000 UTC m=+700338.628641510)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Cleaning up old replicasets, experiments, and analysis runs" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="No changes to canary ingress - skipping patch" ingress=argomyapp-argomyapp.grpc-canary namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciling StableRS" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciling new ReplicaSet 'argomyapp-7cb9fcbbf8'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciling old replica sets" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="No status changes. Skipping patch" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciliation completed" namespace=myapp rollout=argomyapp time_ms=3.2853510000000004
time="2020-11-01T21:58:05Z" level=info msg="Started syncing rollout at (2020-11-01 21:58:05.34872586 +0000 UTC m=+700338.638603009)" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Cleaning up old replicasets, experiments, and analysis runs" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciling TrafficRouting with type 'Nginx'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="No changes to canary ingress - skipping patch" ingress=argomyapp-argomyapp.grpc-canary namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciling StableRS" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciling new ReplicaSet 'argomyapp-7cb9fcbbf8'" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciling old replica sets" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="No status changes. Skipping patch" namespace=myapp rollout=argomyapp
time="2020-11-01T21:58:05Z" level=info msg="Reconciliation completed" namespace=myapp rollout=argomyapp time_ms=3.1812250000000004
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment] 2020-11-02 22:00
Need to confirm if:
```
        startingStep: 2
```

is the step *index* vs. the step number. I suspect the latter, which means that it should be `startingStep: 3`

**Comment by nestorsokil** [comment] 2020-11-03 08:09
@jessesuen I think it's step number (1-based) as per docs, but I don't think it matters for me
```yaml
steps:
        - analysis:
            templates:
              - templateName: {{ template "app.name" . }}-acceptance
        - setWeight: 10
        - pause: { duration: 2m }
        - setWeight: 25
        - pause: { duration: 2m }
```
I'm ok with background analysis starting on setWeight or on the first pause

**Comment by jessesuen** [comment] 2020-11-03 08:43
@nestorsokil oh I misread the problem as background analysis starting prematurely when you clearly stated that inline is started prematurely. I think this is working as expected then. When you have analysis as the first step, e.g.:

```
        - analysis:
            templates:
              - templateName: {{ template "app.name" . }}-acceptance
```

Then you have a setWeight of 0. Rollout controller does not scale the canary up until there is a non-zero weight. 

What you need is the new upcoming v0.10 feature, to set the canary scale, either with an explicit weight:

```yaml
steps:
- setCanaryScale:
     weight: 100
- analysis:
    templates:
    - templateName: {{ template "app.name" . }}-acceptance
- setCanaryScale:
     matchWeight: true # resets it to default behavior
```

or an explicit replica count:

```yaml
steps:
- setCanaryScale:
     replicas: 1
- analysis:
    templates:
    - templateName: {{ template "app.name" . }}-acceptance
- setCanaryScale:
     matchWeight: true # resets it to default behavior
```

See https://github.com/argoproj/argo-rollouts/issues/556. If you want to try this out, you can use the `argoproj/argo-rollouts:latest` image.

**Comment by nestorsokil** [comment] 2020-11-03 13:20
@jessesuen cool, that makes sense thank you! Do you have a release schedule or a roadmap somewhere?

**Comment by jessesuen** [comment] 2020-11-03 19:21
v0.10 will be out within 3 weeks.

**Comment by jessesuen** [comment] 2020-11-03 19:21
Duplicate of https://github.com/argoproj/argo-rollouts/issues/556

**Closed by jessesuen** 2020-11-03 19:21 UTC
Labels: works-for-me
