### ISSUE TITLE
argo-rollouts Dashboard not supporting Rollback

### ISSUE THREAD

**Issue by himanshuupadhyay101** [argoproj/argo-rollouts#2459] opened 2022-12-07 15:28 UTC
**Describe the bug**
When using a Rollouts ``Dashboard`` that uses ``workloadRef`` :
- The "Rollback" button to rollback to previous revisions don't work -- clicking it doesn't do anything. 
- The same issue is also been commented on another issue that is already closed [here](https://github.com/argoproj/argo-rollouts/issues/1525#issuecomment-1324502222)
- However Rollback is working fine with CLI, but we need to rollback from UI to rollback faster in case of any issues.
- According to our findings, In the ``controller`` code the ``workloadref`` is handled that is why it works with CLI whereas it is not handled in the ``Dashboard`` code [here](https://github.com/argoproj/argo-rollouts/blob/v1.3.1/ui/src/app/components/rollout/rollout.tsx#L154)

![image](https://user-images.githubusercontent.com/70565558/206656054-88384ef0-8139-4e92-aba4-975091ed8354.png)

**Version**
v1.3.1+b0b95ca

**Logs**

```
# Logs for the entire controller:
time="2022-12-07T14:45:52Z" level=info msg="Start processing" resource=production/registry-live
time="2022-12-07T14:45:52Z" level=info msg="Started syncing rollout" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live
time="2022-12-07T14:45:52Z" level=info msg="Found 1 TrafficRouting Reconcilers" namespace=production rollout=registry-live
time="2022-12-07T14:45:52Z" level=info msg="Reconciling TrafficRouting with type 'Istio'" namespace=production rollout=registry-live
time="2022-12-07T14:45:52Z" level=info msg="No StableRS exists to reconcile or matches newRS" namespace=production rollout=registry-live
time="2022-12-07T14:45:52Z" level=info msg="No Steps remain in the canary steps" namespace=production rollout=registry-live
time="2022-12-07T14:45:52Z" level=info msg="Trigger on-analysis-run-failed result: [{[0].2jmj7l5rSw0yVb_vlWAYkK_YBwk  [analysis-run-failed] false}]" resource=production/registry-live
time="2022-12-07T14:45:52Z" level=info msg="Trigger on-rollout-aborted result: [{[0].2jmj7l5rSw0yVb_vlWAYkK_YBwk  [rollout-aborted] false}]" resource=production/registry-live
time="2022-12-07T14:45:52Z" level=info msg="Trigger on-rollout-completed result: [{[0].2jmj7l5rSw0yVb_vlWAYkK_YBwk  [rollout-completed] false}]" resource=production/registry-live
time="2022-12-07T14:45:52Z" level=info msg="Processing completed" resource=production/registry-live
time="2022-12-07T14:45:52Z" level=info msg="No status changes. Skipping patch" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live
time="2022-12-07T14:45:52Z" level=info msg="Reconciliation completed" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live time_ms=4.829497
time="2022-12-07T14:45:53Z" level=info msg="Started syncing rollout" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live
time="2022-12-07T14:45:53Z" level=info msg="Found 1 TrafficRouting Reconcilers" namespace=production rollout=registry-live
time="2022-12-07T14:45:53Z" level=info msg="Reconciling TrafficRouting with type 'Istio'" namespace=production rollout=registry-live
time="2022-12-07T14:45:53Z" level=info msg="No StableRS exists to reconcile or matches newRS" namespace=production rollout=registry-live
time="2022-12-07T14:45:53Z" level=info msg="No Steps remain in the canary steps" namespace=production rollout=registry-live
time="2022-12-07T14:45:53Z" level=info msg="No status changes. Skipping patch" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live
time="2022-12-07T14:45:53Z" level=info msg="Reconciliation completed" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live time_ms=4.3544719999999995
time="2022-12-07T14:45:53Z" level=info msg="Started syncing Analysis at (2022-12-07 14:45:53.154596645 +0000 UTC m=+112960.467003381)" analysisrun=registry-live-7b5876c4f7-25 namespace=production
time="2022-12-07T14:45:53Z" level=info msg="Started syncing Analysis at (2022-12-07 14:45:53.154799472 +0000 UTC m=+112960.467206208)" analysisrun=registry-live-8495bf958b-27 namespace=production
time="2022-12-07T14:45:53Z" level=info msg="No status changes. Skipping patch" analysisrun=registry-live-7b5876c4f7-25 namespace=production
time="2022-12-07T14:45:53Z" level=info msg="Reconciliation completed" analysisrun=registry-live-7b5876c4f7-25 namespace=production time_ms=0.633641
time="2022-12-07T14:45:53Z" level=info msg="Started syncing Analysis at (2022-12-07 14:45:53.155261017 +0000 UTC m=+112960.467667753)" analysisrun=registry-live-95c9686b4-26 namespace=production
time="2022-12-07T14:45:53Z" level=info msg="No status changes. Skipping patch" analysisrun=registry-live-8495bf958b-27 namespace=production
time="2022-12-07T14:45:53Z" level=info msg="Reconciliation completed" analysisrun=registry-live-8495bf958b-27 namespace=production time_ms=0.5868289999999999
time="2022-12-07T14:45:53Z" level=info msg="Started syncing Analysis at (2022-12-07 14:45:53.155439382 +0000 UTC m=+112960.467846118)" analysisrun=registry-live-8495bf958b-29 namespace=production
time="2022-12-07T14:45:53Z" level=info msg="No status changes. Skipping patch" analysisrun=registry-live-95c9686b4-26 namespace=production
time="2022-12-07T14:45:53Z" level=info msg="Reconciliation completed" analysisrun=registry-live-95c9686b4-26 namespace=production time_ms=0.481905
time="2022-12-07T14:45:53Z" level=info msg="Started syncing Analysis at (2022-12-07 14:45:53.155767473 +0000 UTC m=+112960.468174219)" analysisrun=registry-live-54f74bdb4b-28 namespace=production
time="2022-12-07T14:45:53Z" level=info msg="No status changes. Skipping patch" analysisrun=registry-live-8495bf958b-29 namespace=production
time="2022-12-07T14:45:53Z" level=info msg="Reconciliation completed" analysisrun=registry-live-8495bf958b-29 namespace=production time_ms=0.576349
time="2022-12-07T14:45:53Z" level=info msg="No status changes. Skipping patch" analysisrun=registry-live-54f74bdb4b-28 namespace=production
time="2022-12-07T14:45:53Z" level=info msg="Reconciliation completed" analysisrun=registry-live-54f74bdb4b-28 namespace=production time_ms=0.5014559999999999
time="2022-12-07T14:45:53Z" level=info msg="Started syncing rollout" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live
time="2022-12-07T14:45:53Z" level=info msg="Found 1 TrafficRouting Reconcilers" namespace=production rollout=registry-live
time="2022-12-07T14:45:53Z" level=info msg="Reconciling TrafficRouting with type 'Istio'" namespace=production rollout=registry-live
time="2022-12-07T14:45:53Z" level=info msg="No StableRS exists to reconcile or matches newRS" namespace=production rollout=registry-live
time="2022-12-07T14:45:53Z" level=info msg="No Steps remain in the canary steps" namespace=production rollout=registry-live
time="2022-12-07T14:45:53Z" level=info msg="No status changes. Skipping patch" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live
time="2022-12-07T14:45:53Z" level=info msg="Reconciliation completed" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live time_ms=4.231038000000001
time="2022-12-07T15:00:52Z" level=info msg="Start processing" resource=production/registry-live
time="2022-12-07T15:00:52Z" level=info msg="Started syncing rollout" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live
time="2022-12-07T15:00:52Z" level=info msg="Found 1 TrafficRouting Reconcilers" namespace=production rollout=registry-live
time="2022-12-07T15:00:52Z" level=info msg="Reconciling TrafficRouting with type 'Istio'" namespace=production rollout=registry-live
time="2022-12-07T15:00:52Z" level=info msg="No StableRS exists to reconcile or matches newRS" namespace=production rollout=registry-live
time="2022-12-07T15:00:52Z" level=info msg="No Steps remain in the canary steps" namespace=production rollout=registry-live
time="2022-12-07T15:00:52Z" level=info msg="Trigger on-rollout-aborted result: [{[0].2jmj7l5rSw0yVb_vlWAYkK_YBwk  [rollout-aborted] false}]" resource=production/registry-live
time="2022-12-07T15:00:52Z" level=info msg="Trigger on-rollout-completed result: [{[0].2jmj7l5rSw0yVb_vlWAYkK_YBwk  [rollout-completed] false}]" resource=production/registry-live
time="2022-12-07T15:00:52Z" level=info msg="Trigger on-analysis-run-failed result: [{[0].2jmj7l5rSw0yVb_vlWAYkK_YBwk  [analysis-run-failed] false}]" resource=production/registry-live
time="2022-12-07T15:00:52Z" level=info msg="Processing completed" resource=production/registry-live
time="2022-12-07T15:00:52Z" level=info msg="No status changes. Skipping patch" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live
time="2022-12-07T15:00:52Z" level=info msg="Reconciliation completed" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live time_ms=4.90803
time="2022-12-07T15:00:53Z" level=info msg="Started syncing rollout" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live
time="2022-12-07T15:00:53Z" level=info msg="Found 1 TrafficRouting Reconcilers" namespace=production rollout=registry-live
time="2022-12-07T15:00:53Z" level=info msg="Reconciling TrafficRouting with type 'Istio'" namespace=production rollout=registry-live
time="2022-12-07T15:00:53Z" level=info msg="No StableRS exists to reconcile or matches newRS" namespace=production rollout=registry-live
time="2022-12-07T15:00:53Z" level=info msg="No Steps remain in the canary steps" namespace=production rollout=registry-live
time="2022-12-07T15:00:53Z" level=info msg="No status changes. Skipping patch" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live
time="2022-12-07T15:00:53Z" level=info msg="Reconciliation completed" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live time_ms=4.530187
time="2022-12-07T15:00:53Z" level=info msg="Started syncing Analysis at (2022-12-07 15:00:53.155715158 +0000 UTC m=+113860.468121904)" analysisrun=registry-live-54f74bdb4b-28 namespace=production
time="2022-12-07T15:00:53Z" level=info msg="Started syncing Analysis at (2022-12-07 15:00:53.156039269 +0000 UTC m=+113860.468446005)" analysisrun=registry-live-7b5876c4f7-25 namespace=production
time="2022-12-07T15:00:53Z" level=info msg="Started syncing Analysis at (2022-12-07 15:00:53.156234875 +0000 UTC m=+113860.468641611)" analysisrun=registry-live-8495bf958b-27 namespace=production
time="2022-12-07T15:00:53Z" level=info msg="No status changes. Skipping patch" analysisrun=registry-live-54f74bdb4b-28 namespace=production
time="2022-12-07T15:00:53Z" level=info msg="Reconciliation completed" analysisrun=registry-live-54f74bdb4b-28 namespace=production time_ms=0.62153
time="2022-12-07T15:00:53Z" level=info msg="No status changes. Skipping patch" analysisrun=registry-live-7b5876c4f7-25 namespace=production
time="2022-12-07T15:00:53Z" level=info msg="Reconciliation completed" analysisrun=registry-live-7b5876c4f7-25 namespace=production time_ms=1.003752
time="2022-12-07T15:00:53Z" level=info msg="Started syncing Analysis at (2022-12-07 15:00:53.157514747 +0000 UTC m=+113860.469921493)" analysisrun=registry-live-95c9686b4-26 namespace=production
time="2022-12-07T15:00:53Z" level=info msg="Started syncing Analysis at (2022-12-07 15:00:53.158137427 +0000 UTC m=+113860.470544173)" analysisrun=registry-live-8495bf958b-29 namespace=production
time="2022-12-07T15:00:53Z" level=info msg="No status changes. Skipping patch" analysisrun=registry-live-8495bf958b-27 namespace=production
time="2022-12-07T15:00:53Z" level=info msg="Reconciliation completed" analysisrun=registry-live-8495bf958b-27 namespace=production time_ms=2.712758
time="2022-12-07T15:00:53Z" level=info msg="No status changes. Skipping patch" analysisrun=registry-live-95c9686b4-26 namespace=production
time="2022-12-07T15:00:53Z" level=info msg="Reconciliation completed" analysisrun=registry-live-95c9686b4-26 namespace=production time_ms=1.4681080000000002
time="2022-12-07T15:00:53Z" level=info msg="No status changes. Skipping patch" analysisrun=registry-live-8495bf958b-29 namespace=production
time="2022-12-07T15:00:53Z" level=info msg="Reconciliation completed" analysisrun=registry-live-8495bf958b-29 namespace=production time_ms=2.5294119999999998
time="2022-12-07T15:00:53Z" level=info msg="Started syncing rollout" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live
time="2022-12-07T15:00:53Z" level=info msg="Found 1 TrafficRouting Reconcilers" namespace=production rollout=registry-live
time="2022-12-07T15:00:53Z" level=info msg="Reconciling TrafficRouting with type 'Istio'" namespace=production rollout=registry-live
time="2022-12-07T15:00:53Z" level=info msg="No StableRS exists to reconcile or matches newRS" namespace=production rollout=registry-live
time="2022-12-07T15:00:53Z" level=info msg="No Steps remain in the canary steps" namespace=production rollout=registry-live
time="2022-12-07T15:00:53Z" level=info msg="No status changes. Skipping patch" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live
time="2022-12-07T15:00:53Z" level=info msg="Reconciliation completed" generation=8 namespace=production resourceVersion=188516604 rollout=registry-live time_ms=4.796266
```

---

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment] 2022-12-15 03:41
Related https://github.com/argoproj/argo-rollouts/issues/2259

**Comment by himanshuupadhyay101** [comment] 2023-01-04 17:50
> Related #2259

In my case it doesn't rollbacks to the previous revision via UI however in #2259 it was still rollbacking to previous revision.

**Comment by zachaller** [comment] 2023-01-16 15:53
I am unable to reproduce this using the example here https://github.com/argoproj/argo-rollouts/tree/master/examples/workload-ref

**Comment by meeech** [comment] 2023-02-24 13:45
I just tested on v1.4.0+e40c9fe and can confirm rollback works when using a rollout with workloadRef to a deployment.

**Comment by tukak** [comment] 2023-03-02 15:17
I think this was fixed in https://github.com/argoproj/argo-rollouts/commit/22ff2c4bddfc62de759a9379a3af7789cff4980c

**Closed** 2023-03-14 02:11 UTC
Labels: bug, no-issue-activity, awaiting-response
