### ISSUE TITLE
Controller panics at startup during ListAndWatch

### ISSUE THREAD

**Issue by cronik** [argoproj/argo-rollouts#471] opened 2020-04-14 22:02 UTC
The argo-rollouts controller is crashing due to a nil pointer deference at startup. Not sure if any of the dependency updates in `0.8.0` caused a regression with k8s `1.13`. Reverting back to `0.7.2` the controller started normally.

Argo Rollouts Version: 0.8.0
Kubernetes Version: 1.13.5

```
$ kubectl logs argo-rollouts-6bc84b476d-smrwb -f
time="2020-04-14T21:42:05Z" level=info msg="Creating event broadcaster"
time="2020-04-14T21:42:05Z" level=info msg="Setting up event handlers"
time="2020-04-14T21:42:05Z" level=info msg="Setting up experiments event handlers"
time="2020-04-14T21:42:05Z" level=info msg="Setting up analysis event handlers"
time="2020-04-14T21:42:05Z" level=info msg="Waiting for controller's informer caches to sync"
I0414 21:42:35.629285       1 trace.go:116] Trace[2019727887]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105 (started: 2020-04-14 21:42:05.628701978 +0000 UTC m=+0.072597013) (total time: 30.000495847s):
Trace[2019727887]: [30.000495847s] [30.000495847s] END
E0414 21:42:35.629378       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 119 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x16de020, 0x282f0a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x16de020, 0x282f0a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0000ca790, 0xc0004d1280, 0xc0002c2540, 0xc000633b60, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:222 +0xb46
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0000ca790, 0xc0002c2540, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:247 +0x17c
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:152 +0x33
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0007ba6f0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005a3ef0, 0x3b9aca00, 0x0, 0xc0007ba701, 0xc0002c2540)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0000ca790, 0xc0002c2540)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:151 +0x16b
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:54 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0006dc020, 0xc0003cc280)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:69 +0x62
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference

goroutine 119 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x16de020, 0x282f0a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0000ca790, 0xc0004d1280, 0xc0002c2540, 0xc000633b60, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:222 +0xb46
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0000ca790, 0xc0002c2540, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:247 +0x17c
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:152 +0x33
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0007ba6f0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005a3ef0, 0x3b9aca00, 0x0, 0xc0007ba701, 0xc0002c2540)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0000ca790, 0xc0002c2540)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:151 +0x16b
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:54 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0006dc020, 0xc0003cc280)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:69 +0x62
```

The only modification to the base deployment is the addition of the new `nginx-ingress-classes` args.
```yaml
spec:
   containers:
      - args:
        - --nginx-ingress-classes
        - ""
        - --nginx-ingress-classes
        - nginx
        - --nginx-ingress-classes
        - fwd-headers
        - --nginx-ingress-classes
        - long-txn
        - --nginx-ingress-classes
        - ipe
        command:
        - /bin/rollouts-controller
        image: <internal-repo>/argo-rollouts:v0.8.0
```

**Comment by jessesuen** [comment] 2020-04-15 18:29
@cronik we are having trouble reproducing this. When you did the upgrade, did you also apply all the necessary RBAC changes as well? Or did you only change the image + args?

**Comment by jessesuen** [comment] 2020-04-15 18:35
One possibility is argo-rollouts upgraded the k8s client version to v1.17 in v0.8, so it's possible theres a go-client compatibility issue with k8s v1.13. Not sure if you are able to provide another data point of using rollouts with a higher version k8s cluster, but that would be good to know.

**Comment by cronik** [comment] 2020-04-15 18:40
Looks like all the resources were updated:

```
+ kustomize build argo-rollouts/base
+ kubectl apply --validate=false -f -
customresourcedefinition.apiextensions.k8s.io/analysisruns.argoproj.io configured
customresourcedefinition.apiextensions.k8s.io/analysistemplates.argoproj.io configured
customresourcedefinition.apiextensions.k8s.io/experiments.argoproj.io configured
customresourcedefinition.apiextensions.k8s.io/rollouts.argoproj.io configured
serviceaccount/argo-rollouts configured
role.rbac.authorization.k8s.io/argo-rollouts-role configured
clusterrole.rbac.authorization.k8s.io/argo-rollouts-aggregate-to-admin configured
clusterrole.rbac.authorization.k8s.io/argo-rollouts-aggregate-to-edit configured
clusterrole.rbac.authorization.k8s.io/argo-rollouts-aggregate-to-view configured
clusterrole.rbac.authorization.k8s.io/argo-rollouts-clusterrole configured
rolebinding.rbac.authorization.k8s.io/argo-rollouts-role-binding configured
clusterrolebinding.rbac.authorization.k8s.io/argo-rollouts-clusterrolebinding configured
service/argo-rollouts-metrics configured
deployment.apps/argo-rollouts configured
```

I'll do some more testing to see if I can get more information.

**Comment by jessesuen** [comment] 2020-04-15 19:17
I noticed that the panic perfectly aligns 30 seconds from when we start waiting for the informer caches to sync, which is too coincidental. 

```
time="2020-04-14T21:42:05Z" level=info msg="Waiting for controller's informer caches to sync"
I0414 21:42:35.629285       1 trace.go:116] Trace[2019727887]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105 (started: 2020-04-14 21:42:05.628701978 +0000 UTC m=+0.072597013) (total time: 30.000495847s):
Trace[2019727887]: [30.000495847s] [30.000495847s] END
```

v0.8 added watching ingresses and secret informers. The panic is happening when we are waiting for the informers to sync.

Could you also add `["--gloglevel", "8"]` to the controller arguments and then paste the logs leading up to the panic? This will log the K8s API calls and response codes which the controller is making.

Also, do you know how many ingresses resources are in this cluster ? One shot in the dark idea that came to mind, is if theres possibly some issues with the initial syncing of the informers caused by sheer number of the resources.

We may need to provide an instrumented build which has some additional logging too after these.

**Comment by cronik** [comment] 2020-04-15 20:46
I think it might might be isolated to that specific cluster I deployed it to. It's a POC cluster so its current state is probably questionable. I deployed to a couple other clusters running slightly different versions (1.13.9, 1.13.12) and the controller started normally. I went back and redeployed again to the poc cluster (1.13.5) and it's running fine now.

I'll keep an eye on things, but for now I'll chalk it up to a sketchy cluster.

Thanks for the support 👍

**Comment by jessesuen** [comment] 2020-07-31 22:51
We hit this on our own v1.15 cluster with Argo Rollouts v0.8.1.

Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

Restarting the controller allowed it to work again.

```
I0728 22:10:59.034863       1 trace.go:116] Trace[140954425]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105 (started: 2020-07-28 22:10:29.033864972 +0000 UTC m=+0.028264181) (total time: 30.000897405s):
Trace[140954425]: [30.000897405s] [30.000897405s] END
E0728 22:10:59.034880       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 149 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x16de020, 0x282f0a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x16de020, 0x282f0a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc00051e0b0, 0xc00054c080, 0xc000640180, 0xc000619b60, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:222 +0xb46
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc00051e0b0, 0xc000640180, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:247 +0x17c
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:152 +0x33
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005e6ef0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000647ef0, 0x3b9aca00, 0x0, 0xc0005e6e01, 0xc000640180)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc00051e0b0, 0xc000640180)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:151 +0x16b
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:54 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000464290, 0xc0003c20a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:69 +0x62
I0728 22:10:59.034690       1 trace.go:116] Trace[2019727887]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105 (started: 2020-07-28 22:10:29.033769361 +0000 UTC m=+0.028168570) (total time: 30.000827837s):
Trace[2019727887]: [30.000827837s] [30.000827837s] END
E0728 22:10:59.034995       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 144 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x16de020, 0x282f0a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x16de020, 0x282f0a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0000268f0, 0xc0004a1680, 0xc000640180, 0xc0005ecb60, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:222 +0xb46
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0000268f0, 0xc000640180, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:247 +0x17c
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:152 +0x33
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005e86f0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005a3ef0, 0x3b9aca00, 0x0, 0xc0005e8601, 0xc000640180)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0000268f0, 0xc000640180)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:151 +0x16b
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:54 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000539860, 0xc000105280)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:69 +0x62
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference

goroutine 149 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x16de020, 0x282f0a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc00051e0b0, 0xc00054c080, 0xc000640180, 0xc000619b60, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:222 +0xb46
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc00051e0b0, 0xc000640180, 0x0, 0x0)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:247 +0x17c
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:152 +0x33
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005e6ef0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000647ef0, 0x3b9aca00, 0x0, 0xc0005e6e01, 0xc000640180)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc00051e0b0, 0xc000640180)
	/go/pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:151 +0x16b
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:54 +0x2e
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000464290, 0xc0003c20a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.17.4-beta.0/pkg/util/wait/wait.go:69 +0x62
```

**Comment by jessesuen** [comment] 2020-10-24 09:55
Closing since we haven't seen this since.

**Closed by jessesuen** 2020-10-24 09:55 UTC
Labels: bug
