### ISSUE TITLE
"Abort" did not stop failed blue green

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo-rollouts#1259] opened 2021-06-08 19:00 UTC
## Summary 

Rollout was performing blue green upgrade. The new version failed to start due to internal app error. The user trigger "Abort" action using Argo CD UI. The "Abort" button got grey out but nothing happened: "blue" pods was not deleted.

## Diagnostics

What version of Argo Rollouts are you running?

v0.10.2

**Comment by jessesuen** [comment] 2021-06-09 03:22
As discussed, an aborted rollout does not tear down the new stack. There is an upcoming feature to support this:
https://github.com/argoproj/argo-rollouts/pull/1160

**Comment by jessesuen** [comment] 2021-06-09 03:23
Duplicate of https://github.com/argoproj/argo-rollouts/issues/941

**Closed by jessesuen** 2021-06-09 03:22 UTC
Labels: bug
