### ISSUE TITLE
Scale down preview replica set when the analysis run fails in bg

### ISSUE THREAD

**Issue by jgquach3** [argoproj/argo-rollouts#793] opened 2020-10-19 18:47 UTC
# Summary
- Currently within bg, the preview replica set does not scale down when an analysis run fails. 

What change needs making?
- The scale down annotation can be added on the preview replica set in the case of an analysis run failure.
PR - https://github.com/argoproj/argo-rollouts/compare/master...jgquach3:preview-scale-down?expand=1
(currently by default it will scale down, but another key can be added onto the rollout CR to add the annotation or not)

# Use Cases

When would you use this?
If a preview replica set is left up, it could be taking up k8s resources. It also makes sense to remove the preview in prod settings to prevent potential problems. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment] 2021-06-17 21:35
Closing as duplicate of https://github.com/argoproj/argo-rollouts/issues/941

**Closed by jessesuen** 2021-06-17 21:35 UTC
Labels: enhancement
