### ISSUE TITLE
Rollout abort scales down stable ReplicaSet if there is no rollout in progress

### ISSUE THREAD

**Issue by kev1n11** [argoproj/argo-rollouts#1292] opened 2021-06-18 18:27 UTC
## Summary 

For _canary_ strategy, calling `rollouts abort` when there's **no** current rollout would scale the **stable** _ReplicaSet_ to 0.

This was surprising, I would have thought this action to be a no-op or at most revert to the _ReplicaSet_ prior to stable.

This is what [the doc](https://argoproj.github.io/argo-rollouts/generated/kubectl-argo-rollouts/kubectl-argo-rollouts_abort.html ) for this command says

> This command stops progressing the current rollout and reverts all steps. The previous ReplicaSet will be active.

## Diagnostics

What version of Argo Rollouts are you running?
`v0.10.2`

```
# Paste the logs from the rollout controller
Started syncing rollout at (2021-06-15 23:29:12.699651128 +0000 UTC m=+754407.503616433)
Reconciling TrafficRouting with type 'Istio'
Reconciling StableRS
No StableRS exists to reconcile or matches newRS
Reconciling new ReplicaSet 'foo-859bb5fdfb'
Not finished reconciling new ReplicaSet 'foo-859bb5fdfb'
Not finished reconciling ReplicaSets
Event(v1.ObjectReference{Kind:\"Rollout\", UID:\"...\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"xyz\", FieldPath:\"\"}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled down replica set foo-859bb5fdfb from 7 to 0
Reconciliation completed

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by kev1n11** [comment] 2021-06-18 18:36
Looking through the code, it SEEMs what happens is (I've checked both `v0.10.2` and latest `v1.0.2`):

- `reconcileCanaryReplicaSets()` would try to reconcile the **stable** RS first, and then **new** RS later
- in this case `reconcileCanaryStableReplicaSet()` a a no-op because the stable and new RS are the same
- when `reconcileNewReplicaSet()`  the desired count is derived to be 0 because the `Status` is `abort` as per this function

```
func GetCurrentSetWeight(rollout *v1alpha1.Rollout) int32 {
	if rollout.Status.Abort {
		return 0
	}
	...
}
```

Naive me thinks if **stable** and **new** RS are the same, we could skip reconciling the new RS?

**Comment by huikang** [comment] 2021-06-21 15:22
Hi, @kev1n11 , somehow I could not reproduce this behavior; following is my steps:

1. Create a rollout resource
2. Update the image tag of the container and fully promote to healthy.

My understanding is that after step 2, there is no current rollout.

3. Abort the rollout` abort rollouts-demo` 

```
Name:            rollouts-demo
Namespace:       default
Status:          ✖ Degraded
Message:         RolloutAborted: Rollout aborted update to revision 1
Strategy:        Canary
  Step:          6/6
  SetWeight:     0
  ActualWeight:  100
Images:          argoproj/rollouts-demo:blue (stable)
Replicas:
  Desired:       5
  Current:       5
  Updated:       5
  Ready:         5
  Available:     5

NAME                                       KIND        STATUS      AGE  INFO
⟳ rollouts-demo                            Rollout     ✖ Degraded  20s  
└──# revision:1                                                         
   └──⧉ rollouts-demo-6668595956           ReplicaSet  ✔ Healthy   10s  stable
      ├──□ rollouts-demo-6668595956-2tdcn  Pod         ✔ Running   10s  ready:1/1
      ├──□ rollouts-demo-6668595956-5j5xf  Pod         ✔ Running   10s  ready:1/1
      ├──□ rollouts-demo-6668595956-dnrdd  Pod         ✔ Running   10s  ready:1/1
      ├──□ rollouts-demo-6668595956-fgsnw  Pod         ✔ Running   10s  ready:1/1
      └──□ rollouts-demo-6668595956-j9pwv  Pod         ✔ Running   10s  ready:1/1
```

The results show the stable RS is still running. Did I miss any thing in reproducing the behavior.

**Comment by kev1n11** [comment] 2021-06-24 05:48
@huikang Thanks for checking.

I also can't reproduce it with a minimal example for both versions of Argo `v0.10.2` and `v1.0.2`. It's however 100% reproducible in many repos and env we have running `v0.10.2`.

FWIW we use Istio if that makes any difference. Would you have an example with Istio handy to quickly try it out? 

If not I'll try to construct a minimal reproducible example.

**Comment by huikang** [comment] 2021-06-24 14:37
> 
> You are right. I also can't reproduce it with a minimal example for both versions of Argo `v0.10.2` and `v1.0.2`. It's however 100% reproducible in many repos we have running `v0.10.2` (albeit similar configs).
> 

If I understand the above correctly, is this bug only reproducible in v0.10.2 for your repo?

> FWIW we use Istio if that makes any difference. Would you have an example with Istio handy to quickly try it out?

Sure, will test a rollout with istio using both argo-rollouts `v0.10.2` and the `latest master`.

**Comment by kev1n11** [comment] 2021-07-05 14:08
@huikang For me, this is reproducible for both version `v0.10.2`  and then still reproducible after upgrading the controller to`lastest` 

I basically followed https://argoproj.github.io/argo-rollouts/getting-started/istio/

### Istio version
```
> istioctl version
client version: 1.10.1
control plane version: 1.10.1
data plane version: none
```

Istio Op
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
```

### Installation
```
kubectl create namespace argo-rollouts
kubectl apply -n argo-rollouts -f https://raw.githubusercontent.com/argoproj/argo-rollouts/v0.10.2/manifests/install.yaml
```

### Set up
```
kubens argo-rollouts
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-rollouts/master/docs/getting-started/istio/rollout.yaml
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-rollouts/master/docs/getting-started/istio/services.yaml
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-rollouts/master/docs/getting-started/istio/virtualsvc.yaml
kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-rollouts/master/docs/getting-started/istio/gateway.yaml
```

### Reproducing steps
```
kubectl argo rollouts set image rollouts-demo rollouts-demo=argoproj/rollouts-demo:yellow
kubectl argo rollouts promote rollouts-demo
```

Then call abort
```
kubectl argo rollouts abort rollouts-demo
```

**Comment by huikang** [comment] 2021-07-05 14:49
@kev1n11 , thanks for the the detailed instructions to reproduce the error. Now I can reproduce the error, which seems only happened to the rollout with traffic management.

@jessesuen , I can look into this issue; please assign this to me. Thanks.

**Comment by huikang** [comment] 2021-07-09 04:01
@kev1n11 the #1331  should fix this bug. Could you give it a shot? Thanks.

**Closed** 2021-07-13 18:04 UTC
Labels: bug, cherry-pick/release-1.0
