### ISSUE TITLE
Option to scale down current stack upon abort

### ISSUE THREAD

**Issue by artem-nefedov** [argoproj/argo-rollouts#941] opened 2021-01-13 15:18 UTC
## Summary 

What happened/what you expected to happen?

If you run analysis as a step after `setCanaryScale` and it fails, canary replicas created by `setCanaryScale` will run indefinitely (until new version is deployed) after rollback is performed, even though they are never going to be used for anything. It should either be cleaned up by default (similar to replicas created by `setWeight`), or there should be an option to do it.

In the described scenario, there are no `setWeight` steps prior to `setCanaryScale`.

## Diagnostics

What version of Argo Rollouts are you running?

v0.10.2

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment] 2021-01-13 19:49
When you say "after rollback is performed" do you mean when the rollout is aborted? If so, this is the current design. The rationale was that retrying analysis would not have to redo all the spin-up time of scheduling pods, and warm up. Note that BlueGreen has a similar behavior in that the new stack is not terminated when rollback is aborted caused by analysis failure. 

> or there should be an option to do it.

This is not the first time this behavior has been requested. If we were to introduce a flag like `scaleDownOnAbort: true` would that satisfy your use case?

**Comment by artem-nefedov** [comment] 2021-01-13 20:03
> When you say "after rollback is performed" do you mean when the rollout is aborted?

Yes, I mean when it is aborted automatically due to new version failing on analysis.

> If we were to introduce a flag like scaleDownOnAbort: true would that satisfy your use case?

Yes, I believe that would do it.

**Comment by huikang** [comment] 2021-05-05 05:13
@jessesuen , do you think the proposed change is also applicable to an aborted b/g rollout?

**Comment by huikang** [comment] 2021-05-05 15:28
This seems related to #793.

@jessesuen , I will write up a change proposal to handle these user stories. Please assign this to me. Thanks.

**Comment by huikang** [comment] 2021-07-20 19:44
@jessesuen , I think we can close this issue.

**Comment by jessesuen** [comment] 2021-07-20 20:54
Fixed in v1.1

**Closed by jessesuen** 2021-07-20 20:54 UTC
Labels: enhancement
