### ISSUE TITLE
failed to watch *v1beta1.ingress: failed to list *v1beta1.ingress

### ISSUE THREAD

**Issue by wang-wayne** [argoproj/argo-rollouts#1800] opened 2022-01-23 13:23 UTC
## Summary 

Failed to install argo-rollouts on k3s.

## Diagnostics

The version of argo-rollouts is v1.1.1
The version of k3s is v1.23.1+k3s2. 
The version of Kubernetes is v1.23.1.

The pod of argo-rollouts failed to start.
```
failed to watch *v1beta1.ingress: failed to list *v1beta1.ingress
```

When I set k3s version to v1.21.8+k3s2. The installation of argo-rollouts is successful.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by alexmt** [comment] 2022-01-24 19:06
Following command should help to create k8s cluster with the right version. 

```
k3d cluster create argocd-test --image rancher/k3s:v1.21.8+k3s2
```

Hopefully it will help to reproduce it

**Comment by alexmt** [comment] 2022-01-24 19:13
Tried myself and reproduced the same error :)

**Comment by alexmt** [comment] 2022-01-24 19:39
Just released that this is expected. PR https://github.com/argoproj/argo-rollouts/pull/1655 fixed this issue but the fix is not released yet. So closing the issue since it is already fixed in master

**Closed by alexmt** 2022-01-24 19:39 UTC
Labels: bug

**Comment by leoluz** [comment] 2022-01-24 19:53
@harikrongali if we are cherrypicking for the next release we need both PRs that implements networking.Ingress support:
https://github.com/argoproj/argo-rollouts/pull/1529
https://github.com/argoproj/argo-rollouts/pull/1655

**Comment by sigi4** [comment] 2022-01-27 21:01
I run into this issue and i'm curious what the dependency is that it isn't released yet?

Kubernetes 1.22 is out since August, wouldn't that have broken much more setups?

**Comment by leoluz** [comment] 2022-01-27 21:48
@sigi4 k8s 1.22 removed the support for `v1beta1.Ingress` from the `extensions` package which is the one used by argo-rollouts. Argo-Rollouts 1.2 will be released in the coming weeks and will add support to the new `networking.Ingress`. If you can't wait for the new release, the suggestion is build and deploy from master branch which is what impacted community users did.

**Comment by sigi4** [comment] 2022-01-27 21:55
@leoluz ah interesting. I was just really unsure as it feels this issue would affect much more users.

I pinned it through kustomize, which works fine:
`  - github.com/argoproj/argo-rollouts.git/manifests/cluster-install?ref=b06e83dfbceb3edb32f6cf3b7a6e665124dc9221`
