### ISSUE TITLE
Support multiple VirtualService in Istio canary strategy

### ISSUE THREAD

**Issue by shakti-das** [argoproj/argo-rollouts#1276] opened 2021-06-14 15:53 UTC
# Summary
The current Istio canary strategy allows specifying only a single `VirtualService`. This is not sufficient for advanced setups where the routes are divided into multiple `VirtualService` resources - like north-south route VS, east-west route VS, and delegate VS. 

# Use Cases
In Salesforce, we use multiple `VirtualService` resources linked to a single service. Each service port also gets its own specialized delegate `VirtualService`. The blue/green route for our use-case would actually stay in the multiple delegates. When the Service undergoes a blue/green rollout, we want to update all the linked `VirutalService` resources.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment] 2021-06-15 00:38
Duplicate of https://github.com/argoproj/argo-rollouts/issues/1100

**Closed** 2021-06-15 00:38 UTC
Labels: enhancement
