### ISSUE TITLE
kustomize replaces spec/template/spec/containers

### ISSUE THREAD

**Issue by mtsmfm** [argoproj/argo-rollouts#538] opened 2020-06-17 08:55 UTC
Deployment keeps `image: alpine` but Rollout doesn't even if I use transformer described in https://argoproj.github.io/argo-rollouts/features/kustomize/.

Is this intentional?

https://github.com/mtsmfm/argo-rollout-with-kustomize-issue

```
$ kustomize version
{Version:3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T23:39:00+01:00 GoOs:darwin GoArch:amd64}
```

```
$ kustomize build test-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - image: alpine
        name: test
        resources:
          requests:
            memory: 1Mi
```

```
$ kustomize build test-rollout
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test
spec:
  template:
    spec:
      containers:
      - name: test
        resources:
          requests:
            memory: 1Mi
```

**Comment by jessesuen** [comment] 2020-06-25 12:24
The issue is that kustomize does not support strategic merge patching of custom resources, so the patch you have defined, is actually replacing the entire list of containers. See https://github.com/jessesuen/kustomize-examples/tree/master/strategic-merge-patch-crd-fail for details.

**Comment by jessesuen** [comment] 2020-08-24 11:57
Closing since this is a kustomize limitation. When we reached out to kustomize maintainers about feature parity of native types for CRDs, we were told to follow https://github.com/kubernetes-sigs/kustomize/issues/2339.

**Closed by jessesuen** 2020-08-24 11:57 UTC

**Comment by hjanuschka** [comment] 2020-12-08 19:57
since kubernetes-sigs/kustomize#2339 still not merged, for others who might stumble upon this.


i just used `Deployment`  in the whole kustomize pipeline.
and later on changing resource kind to `Rollout`


kustomization.yaml

```yaml
patches:
- path: patches/transform_to_rollout.json
  target:
    group: apps
    version: v1
    kind: Deployment
    name: frontend

```

transform_to_rollout.json
```json
[
    {
        "op": "replace",
        "path": "/spec/strategy",
        "value": {
            "blueGreen": {
                "autoPromotionEnabled": true,
                "activeService": "frontend"
            }
        }
    },
    {
        "op": "replace",
        "path": "/kind",
        "value": "Rollout"
    },
    {
        "op": "replace",
        "path": "/apiVersion",
        "value": "argoproj.io/v1alpha1"
    }
]
```

if you'd used "commonLables" you also might need to change/add some of them.

**Comment by tsurankov** [comment] 2021-08-06 11:46
@hjanuschka Unfortunately, this removes configMapGenerator's hash because the kind is changed

**Comment by danielamar101-pton** [comment] 2025-10-15 15:26
Any updates here?
