### ISSUE TITLE
argo-rollouts pod in CrashLoopBackOff

### ISSUE THREAD

**Issue by barakakha** [argoproj/argo-rollouts#96] opened 2019-06-03 11:01 UTC
i installed argo-rollouts using the install.yaml but the argo-rollouts constantly failing on
`time="2019-06-03T10:51:20Z" level=info msg="Creating event broadcaster"
time="2019-06-03T10:51:20Z" level=info msg="Setting up event handlers"
time="2019-06-03T10:51:20Z" level=info msg="Starting Rollout controller"
time="2019-06-03T10:51:20Z" level=info msg="Waiting for informer caches to sync"
E0603 10:51:20.412853       1 reflector.go:134] github.com/argoproj/argo-rollouts/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.Rollout: rollouts.argoproj.io is forbidden: User "system:serviceaccount:default:argo-rollouts" cannot list resource "rollouts" in API group "argoproj.io" at the cluster scope
E0603 10:51:20.412853       1 reflector.go:134] github.com/argoproj/argo-rollouts/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.Rollout: rollouts.argoproj.io is forbidden: User "system:serviceaccount:default:argo-rollouts" cannot list resource "rollouts" in API group "argoproj.io" at the cluster scope
log: exiting because of error: log: cannot create log: open /tmp/rollouts-controller.argo-rollouts-694bc885dd-gqmst.unknownuser.log.ERROR.20190603-105120.1: no such file or directory`

what should i do?

**Comment by alexmt** [comment] 2019-06-03 18:32
This will be fixed by https://github.com/argoproj/argo-rollouts/pull/94 . Right now only option is to rollback to either v0.3.0 or wait for v0.3.2. Closing as duplicate of https://github.com/argoproj/argo-rollouts/issues/85

**Closed by alexmt** 2019-06-03 18:32 UTC

**Comment by jessesuen** [comment] 2019-06-03 21:43
Another workaround is to volume mount an emptyDir into /tmp
