### ISSUE TITLE
HPA scaling event (likely scaling down event) seems to affect analysisruns

### ISSUE THREAD

**Issue by schlags** [argoproj/argo-rollouts#2938] opened 2023-08-07 15:01 UTC
### Discussed in https://github.com/argoproj/argo-rollouts/discussions/2935

<div type='discussions-op-text'>

<sup>Originally posted by **schlags** August  4, 2023</sup>
We're noticing some odd behavior in our pre/post-analysisruns for BlueGreen. 
It seems to be a relation where if the HPA scales down the desired pod count in the RS, the reconciliation of pre/post analysis will either terminate the running analysisrun and continue with the rollout, or it will see a completed analysisrun and throw a "Collision" log. Eventually spinning up a `.1` and sometimes a `.2` AnalysisRun.

The former ("Run Terminated" with Success status) is very concerning since it allows our deployment to continue without completing analysis. 

I haven't been able to find any conclusive documentation around how this can be mitigated. Any thoughts?</div>

**Comment by schlags** [comment] 2023-08-07 19:19
Related to #2931

**Comment by jessesuen** [comment] 2023-09-26 18:34
Yep, this is duplicate of https://github.com/argoproj/argo-rollouts/issues/2931

**Closed by jessesuen** 2023-09-26 18:34 UTC
Labels: blue-green, analysis
