### ISSUE TITLE
Web UI: Please put namespace in the URL

### ISSUE THREAD

**Issue by DanTulovsky** [argoproj/argo-rollouts#1709] opened 2021-12-13 16:27 UTC
## Summary 

Please put the namespace into the URL of the dashboard component.  e.g.

http://myhost/rollout/namespace-foo/rollout-bar

It's not clear how the namespace is currently set, but I often end up in a situation where there seems to be a disconnect between the namespace being shown and the Rollout I am trying to see.  e.g. if I am trying to see Rollout "X" in namespace "Y" via:

`http://myhost/rollout/X`

but the namespace dropdown is set to "Z" (I am not sure how it picks what to show), then I don't see anything.

In general, please also consider showing all the namespaces when clicking into the namespace dropdown.  Right now you have to delete the current namespace manually before you can pick a different one (due to auto-complete I assume).

## Diagnostics

What version of Argo Rollouts are you running?

v1.1.0+ff3471a

```
# Paste the logs from the rollout controller

# Logs for the entire controller:
kubectl logs -n argo-rollouts deployment/argo-rollouts

# Logs for a specific rollout:
kubectl logs -n argo-rollouts deployment/argo-rollouts | grep rollout=<ROLLOUTNAME>
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment] 2021-12-14 18:21
Duplicate of https://github.com/argoproj/argo-rollouts/issues/1538

**Closed by jessesuen** 2021-12-14 18:21 UTC
Labels: bug
