### ISSUE TITLE
Argo Rollouts Docs refer to ArgoCD secret/configmap names

### ISSUE THREAD

**Issue by mattvaughan** [argoproj/argo-rollouts#3049] opened 2023-09-21 15:23 UTC
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.

**Describe the bug**

Argo Rollouts docs refer to names of ArgoCD secrets

**To Reproduce**

[View these docs](https://github.com/argoproj/argo-rollouts/blob/57be60a0bb19ca381c2b690e608fabd001aae2d0/docs/generated/notification-services/slack.md?plain=1#L30)

See that it refers to a secret named `argocd-notifications-secret`

**Expected behavior**

Docs refer to the correct secret and config map names. For example, the logs show that Rollouts is looking for a secret named `argo-rollouts-notification-secret`.

**Version**

Helm Chart `2.31.5`

**Logs**

N/A

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by zachaller** [comment] 2023-09-21 16:09
duplicate of: https://github.com/argoproj/argo-rollouts/issues/1680

**Closed** 2024-02-27 17:35 UTC
Labels: bug, docs, no-issue-activity
