### ISSUE TITLE
Operation cannot be fulfilled on replicasets.apps: the object has been modified

### ISSUE THREAD

**Issue by artem-nefedov** [argoproj/argo-rollouts#1775] opened 2022-01-14 15:37 UTC
## Summary 

We sometimes observe the problem where Rollout would be permanently stuck in degraded state due to the error:

```
Message:         RolloutAborted: Rollout aborted update to revision 2: Unable to scale ReplicaSet for template 'canary-preview' to desired replica count '1': Operation cannot be fulfilled on replicasets.apps "podinfo-test-argo-rollouts-55848cf857-2-0-canary-preview": the object has been modified; please apply your changes to the latest version and try again
```

This sometimes happens when experiment tries to scale up preview replica. The issue is very rare. We run a lot of tests, and seen this multiple times already, but when I intentionally wanted to reproduce it to collect info, the test was run ~90 times before it happened.

## Reproduction steps

1. Apply manifests (attached)
2. Wait for rollout to become complete
3. Immediately run `kubectl patch rollout podinfo-test-argo-rollouts --type=json '-p=[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"stefanprodan/podinfo:3.1.1"}]'`
4. Pray for reproduction

## Diagnostics

Argo Rollouts version is v.1.1.1.
k8s version 1.21 (EKS).

After reproducing the issue, I've tried to collect every possible debug info: objects output, controller logs, etc. 
All of that is attached:

- [argo-controller-logs.txt](https://github.com/argoproj/argo-rollouts/files/7871431/argo-controller-logs.txt)
- [plugin-get-rollout.txt](https://github.com/argoproj/argo-rollouts/files/7871432/plugin-get-rollout.txt)
- [manifests.yaml.txt](https://github.com/argoproj/argo-rollouts/files/7871436/manifests.yaml.txt)
- [rollout.yaml.txt](https://github.com/argoproj/argo-rollouts/files/7871441/rollout.yaml.txt)
- [describe-rollout.txt](https://github.com/argoproj/argo-rollouts/files/7871442/describe-rollout.txt)
- [experiment.yaml.txt](https://github.com/argoproj/argo-rollouts/files/7871452/experiment.yaml.txt)
- [describe-experiment.txt](https://github.com/argoproj/argo-rollouts/files/7871454/describe-experiment.txt)
- [rs.yaml.txt](https://github.com/argoproj/argo-rollouts/files/7871456/rs.yaml.txt)
- [describe-rs.txt](https://github.com/argoproj/argo-rollouts/files/7871459/describe-rs.txt)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by jessesuen** [comment] 2022-01-15 00:05
The issue is that resource conflict errors are a fact of life, and the experiment controller needs to accommodate this possibility by retrying/re-reconciling the experiment. I think the fix for this should be easy.

```golang
func (ec *experimentContext) scaleTemplateRS(rs *appsv1.ReplicaSet, template v1alpha1.TemplateSpec, templateStatus *v1alpha1.TemplateStatus, desiredReplicaCount int32, experimentReplicas int32) {
...
	_, _, err := ec.scaleReplicaSetAndRecordEvent(rs, desiredReplicaCount)
	if err != nil { //  check if this is resource conflict error and don't fail.
		templateStatus.Status = v1alpha1.TemplateStatusError
		templateStatus.Message = fmt.Sprintf("Unable to scale ReplicaSet for template '%s' to desired replica count '%v': %v", templateStatus.Name, desiredReplicaCount, err)
	} else {
...
	}
}
```

**Closed** 2022-01-19 00:15 UTC
Labels: bug
