### ISSUE TITLE
refactor to remove mpatch library from rollouts

### ISSUE THREAD

**Issue by harikrongali** [argoproj/argo-rollouts#1653] opened 2021-11-12 19:10 UTC
With latest commit #1545, contributors are seeing failures in running unit tests locally on mac
Reason is with mpatch library. 
```
        	Error Trace:	list_test.go:182
        	Error:      	Received unexpected error:
        	            	permission denied
        	Test:       	TestListNamespaceAndTimestamp
```

**Comment by huikang** [comment] 2021-11-15 03:57
This looks duplicate to  #1605

**Comment by jessesuen** [comment] 2021-12-14 18:01
Duplicate of https://github.com/argoproj/argo-rollouts/issues/1605

**Closed by jessesuen** 2021-12-14 18:01 UTC
Labels: bug
