### ISSUE TITLE
Experiment create service with hardcoded port. 

### ISSUE THREAD

**Issue by jeromeguiard** [argoproj/argo-rollouts#2233] opened 2022-09-07 15:40 UTC
**Describe the bug**

Using experiment in rollout step, it is expected to have a service created to route traffic to it. as describe in this doc: https://github.com/argoproj/argo-rollouts/blob/master/docs/features/experiment.md 

``` 
When a weighted experiment step with traffic routing is used, a service is auto-created for each experiment template. The traffic routers use this service to send traffic to the experiment pods.
```

Created service related to the experiment have port 8080 as targetPort

**To Reproduce**

Start an experiment, in a rollout canary step, set weight for stable and canary. Once experiment start describe created services.

**Expected behavior**

We should have the ability to add service configuration, to have, on ports, the ability to specify Port, TargetPort, Name, multiple ports.

**Screenshots**

from experiments/service.go 

<img width="1279" alt="Screenshot 2022-09-05 at 21 54 32" src="https://user-images.githubusercontent.com/555535/188919531-e4b440a9-3733-401f-876a-3e56280ee783.png">

**Version**

1.2, 1.3

**Logs**

Controller doesn't show error

**Comment by jessesuen** [comment] 2022-09-29 00:26
Yes, this is a bit of an embarrassing bug. I am pretty sure @zachaller is right and `TemplateService` was intended to be used to give full control on the service that was created.

**Comment by alexef** [comment] 2022-10-21 12:32
@jessesuen / @zachaller I assume that the fix for this would be to follow up on https://github.com/argoproj/argo-rollouts/pull/1158 and infer the servicePorts from the Rollout.spec.template.containers, or additionally allow the user to specify the port.

We have an additional use case for this - we use experiments to create a separate workload (different pod labels) that does not receive production traffic (therefore we don't set weight). We would like Argo Rollouts to generate the service in that case as well.

I can start the implementation of the bug fix. Please let me know what you think about also implementing the additional functionality to generate the service on request (via step definition) and not only when weight is set.

**Comment by zachaller** [comment] 2022-10-21 15:17
So we have talked about this a bit and it is a bug however I think the fix we want to implement is to embed the whole service spec into the TemplateService something like:

```
type TemplateService struct{
	corev1.ServiceSpec
}
```

I think we might want to maintain control of the metadata like auto generating names etc. Do you see any issues with this approach? I feel it will be a lot more future proof this way and provide full customization.

**Comment by alexef** [comment] 2022-10-21 15:30
Thanks for the link to #2257, I missed it.

Looking at the code, we control ownership of the generated service using an annotation. This will allow one to override the service name (this is our use case), but keep having it managed by the experiment controller.

I don't see an issue with embedding the whole service spec, assuming empty and partial services are allowed (so one can only override the ports if they want to, and all the other metadata will be copied from the replica set).

Should we keep defaulting to the Replicaset spec ports, when no ports are provided? Or make them mandatory? Not sure how the validation would look like.

I will close #2233 (it was a bit brittle as it copied _all_ ports of all containers) and refactor #2357 to make TemplateService extend corev1.Service.

**Comment by zachaller** [comment] 2022-10-22 13:47
> Should we keep defaulting to the Replicaset spec ports, when no ports are provided? Or make them mandatory? Not sure how the validation would look like.

Would you mind pointing me to the code where we get the ports form the replicaset? I think it probably still makes sense to do that because I am guessing it only does that when the experiment is part of a rollout, and the port issue is only really an issue if you try to submit an standalone experiment?

**Comment by alexef** [comment] 2022-10-22 21:12
I was copying in https://github.com/argoproj/argo-rollouts/pull/2356/files#diff-9160eeeef3ac3a4d98cb24f696d54437422a13d16245d8068373f49384cc7e2fR289-R298, exactly, when the Experiment was part of a Rollout, and at a point we already had a ReplicaSet. 

I'm not carrying it over to #2357 due to concerns around what ports should/should not get exposed.

**Closed** 2022-11-08 16:59 UTC
Labels: bug
