### ISSUE TITLE
Promote at end of deployment rolls traffic back to stable for 30 seconds

### ISSUE THREAD

**Issue by bpoland** [argoproj/argo-rollouts#1826] opened 2022-01-31 22:20 UTC
## Summary 

We're using Rollouts with SMI Traffic splitting (k8s nginx ingress + Linkerd) and have noticed that at the end of a deployment, nearly all traffic gets reverted to the "old" version for about 30 seconds.  Here's a screenshot from our monitoring:
![image](https://user-images.githubusercontent.com/24273909/151880347-eeaf72d0-4e9a-48bb-90e3-375ff33a6cc7.png)

This is a bit naive but my guess as to what's happening:
- TrafficSplit is at 100% canary, Linkerd is sending all traffic to the "new" version
- Deployment completes, rollouts controller simultaneously (I assume):
  - updates the stable service selector to target the "new" RS
  - updates the TrafficSplit to 0 (to send traffic to the "new" version)
  
In my case, it seems that the service selector change takes a little while to be picked up, but Linkerd is fast to read the TrafficSplit change and so when it sends traffic to the "stable" version (which should be the new version), it actually sends traffic to the old version until the service selector change gets picked up.

Obviously seeing traffic revert for a period of time isn't ideal, but this also means that we can't use `dynamicStableScale` since that sends 100% of traffic to almost no "old" pods once they scale down.

I wonder if there could be a (configurable?) delay after the stable service selector is updated to point at the "new" pods, but before the TrafficSplit is updated.  If we allow enough time for both the stable and canary services to point to the "new" pods, then the TrafficSplit change would be a no-op since they'd be targeting the same set of pods.

## Diagnostics

What version of Argo Rollouts are you running?
controller 1.1.1

(let me know if you need logs from when this happens, didn't seem like it would necessarily be helpful)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by harikrongali** [comment] 2022-01-31 22:37
the issue is fixed with https://github.com/argoproj/argo-rollouts/issues/1681 ..

**Comment by harikrongali** [comment] 2022-01-31 22:37
can you validate with the latest of master?

**Comment by bpoland** [comment] 2022-01-31 22:42
Ahh thanks, I didn't realize it was the same fix.  I don't think I can try it this week but will try next week unless there's an RC out by then.

**Closed** 2022-01-31 22:42 UTC
Labels: bug
